### ISSUE TITLE
Please retest with 1.7.0 + -Xuse-k2

### ISSUE THREAD

**Issue by vlsi** [asolntsev/big-app.kotlin#82]
See https://kotlinlang.org/docs/whatsnew17.html#new-kotlin-k2-compiler-for-the-jvm-in-alpha

**Comment by asolntsev** [comment]
@vlsi Thank you for the hint, I have tried with K2 compiler:

* Kotlin 1.7.0: `3m 35s`
* Kotlin 1.7.0-k2: `2m 7s`
